services:
  db:
    image: postgres
    restart: always
    ports:
      - ${DOCKER_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
